# -*- coding: utf-8 -*-
"""Pneumonia Detector

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/146rVWQuLiEXrTHc0vMVMMWkhlxNQJqyU
"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import os
import cv2
import numpy as np

import kagglehub
path = kagglehub.dataset_download("paultimothymooney/chest-xray-pneumonia")

print("Path to dataset files:", path)

gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
  try:
    for gpu in gpus:
      tf.config.experimental.set_memory_growth(gpu, True)
    print("GPU is available and memory growth is set.")
  except RuntimeError as e:
    print(e)

IMG_HEIGHT = 150
IMG_WIDTH = 150
BATCH_SIZE = 32
EPOCHS = 10
DATA_DIR = '/kaggle/input/chest-xray-pneumonia/chest_xray'

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest'
)

val_datagen = ImageDataGenerator(rescale=1./255)
test_datagen = ImageDataGenerator(rescale=1./255)

try:
    train_generator = train_datagen.flow_from_directory(
        os.path.join(DATA_DIR, 'train'),
        target_size=(IMG_HEIGHT, IMG_WIDTH),
        batch_size=BATCH_SIZE,
        class_mode='binary'
    )

    val_generator = val_datagen.flow_from_directory(
        os.path.join(DATA_DIR, 'val'),
        target_size=(IMG_HEIGHT, IMG_WIDTH),
        batch_size=BATCH_SIZE,
        class_mode='binary'
    )

    test_generator = test_datagen.flow_from_directory(
        os.path.join(DATA_DIR, 'test'),
        target_size=(IMG_HEIGHT, IMG_WIDTH),
        batch_size=BATCH_SIZE,
        class_mode='binary',
        shuffle=False  # Important for later evaluation
    )
except Exception as e:
    print(f"Error loading data: {e}")
    print("Please ensure your dataset is correctly organized at the specified path.")
    exit()

model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(IMG_HEIGHT, IMG_WIDTH, 3)),
    MaxPooling2D(pool_size=(2, 2)),

    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D(pool_size=(2, 2)),

    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D(pool_size=(2, 2)),

    Flatten(),

    Dense(512, activation='relu'),
    Dropout(0.5),

    Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.summary()

print("\nStarting model training...")
history = model.fit(
    train_generator,
    steps_per_epoch=train_generator.samples // BATCH_SIZE,
    epochs=EPOCHS,
    validation_data=val_generator,
    validation_steps=val_generator.samples // BATCH_SIZE
)

print("\nEvaluating the model on the test dataset...")
loss, accuracy = model.evaluate(test_generator)
print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")

# --- Save the Trained Model ---
model_filename = 'pneumonia_detector_model.keras'
print(f"\nSaving the trained model to '{model_filename}'...")
model.save(model_filename)
print("Model saved successfully.")

def predict_pneumonia(image_path, model):
    """
    Predicts whether an X-ray image shows signs of pneumonia or is normal.
    """
    try:
        img = cv2.imread(image_path)
        img = cv2.resize(img, (IMG_WIDTH, IMG_HEIGHT))
        img = img / 255.0
        img = np.expand_dims(img, axis=0)

        prediction = model.predict(img)[0][0]
        if prediction > 0.5:
            return f"Pneumonia detected with confidence: {prediction*100:.2f}%"
        else:
            return f"No pneumonia detected with confidence: {(1 - prediction)*100:.2f}%"
    except Exception as e:
        return f"Error during prediction: {e}"

import matplotlib.pyplot as plt
import random

def display_sample_images(data_dir, num_images=5):
    """Displays a few sample images from the NORMAL and PNEUMONIA classes."""
    normal_dir = os.path.join(data_dir, 'test', 'NORMAL')
    pneumonia_dir = os.path.join(data_dir, 'test', 'PNEUMONIA')

    normal_images = [os.path.join(normal_dir, img) for img in os.listdir(normal_dir) if img.endswith('.jpeg')]
    pneumonia_images = [os.path.join(pneumonia_dir, img) for img in os.listdir(pneumonia_dir) if img.endswith('.jpeg')]

    sample_normal = random.sample(normal_images, min(num_images, len(normal_images)))
    sample_pneumonia = random.sample(pneumonia_images, min(num_images, len(pneumonia_images)))

    plt.figure(figsize=(15, 5))

    for i, img_path in enumerate(sample_normal):
        img = cv2.imread(img_path)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        plt.subplot(1, num_images * 2, i + 1)
        plt.imshow(img)
        plt.title('NORMAL')
        plt.axis('off')

    for i, img_path in enumerate(sample_pneumonia):
        img = cv2.imread(img_path)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        plt.subplot(1, num_images * 2, i + num_images + 1)
        plt.imshow(img)
        plt.title('PNEUMONIA')
        plt.axis('off')

    plt.tight_layout()
    plt.show()

display_sample_images(DATA_DIR)

# Example Usage: Predict on a sample image
sample_image_path = os.path.join(DATA_DIR, 'test', 'PNEUMONIA', os.listdir(os.path.join(DATA_DIR, 'test', 'PNEUMONIA'))[0]) # Using the first pneumonia image in the test set as an example
prediction_result = predict_pneumonia(sample_image_path, model)
print(prediction_result)

# Replace "path/to/your/image.jpg" with the actual path to your image file
your_image_path = "/content/images.jpeg"
your_image_path = "/content/Chest-X-ray-normal.jpeg"

# Display the image
from IPython.display import Image, display
display(Image(filename=your_image_path))

# Get and print the prediction
prediction_result = predict_pneumonia(your_image_path, model)
print(prediction_result)

from google.colab import files
from IPython.display import Image, display
import os

uploaded = files.upload()

for filename in uploaded.keys():
  print(f'Processing uploaded file: {filename}')
  try:
    # Display the image
    display(Image(filename))

    # Get and print the prediction
    prediction_result = predict_pneumonia(filename, model)
    print(f"Prediction for {filename}: {prediction_result}")

  except Exception as e:
    print(f"Could not process {filename}: {e}")

"""# Task
Use an API key to fetch chest X-ray images and train a model.

## Research apis

### Subtask:
Identify and research relevant APIs that provide access to chest X-ray images. Evaluate their terms of service, data availability, and access methods.

## Obtain api key

### Subtask:
If required, obtain an API key or credentials to access the chosen API.

## Develop data fetching script

### Subtask:
Write a Python script to connect to the API, fetch images based on criteria (e.g., normal/pneumonia), and save them locally.

## Integrate with training pipeline

### Subtask:
Modify the existing data loading and preprocessing steps to use the newly fetched images.

**Reasoning**:
Update the DATA_DIR variable and modify the ImageDataGenerator calls to use the new data directory.
"""

# Assume the new fetched images are saved in a directory named 'new_chest_xray'
# within the kaggle input directory. Update DATA_DIR accordingly.
DATA_DIR = '/kaggle/input/chest-xray-pneumonia/new_chest_xray' # This needs to be the correct path

try:
    train_generator = train_datagen.flow_from_directory(
        os.path.join(DATA_DIR, 'train'),
        target_size=(IMG_HEIGHT, IMG_WIDTH),
        batch_size=BATCH_SIZE,
        class_mode='binary'
    )

    val_generator = val_datagen.flow_from_directory(
        os.path.join(DATA_DIR, 'val'),
        target_size=(IMG_HEIGHT, IMG_WIDTH),
        batch_size=BATCH_SIZE,
        class_mode='binary'
    )

    test_generator = test_datagen.flow_from_directory(
        os.path.join(DATA_DIR, 'test'),
        target_size=(IMG_HEIGHT, IMG_WIDTH),
        batch_size=BATCH_SIZE,
        class_mode='binary',
        shuffle=False
    )
except Exception as e:
    print(f"Error loading data: {e}")
    print("Please ensure your dataset is correctly organized at the specified path.")
    # Exit is not supported in this environment, reporting failure
    print("Subtask failed: Error loading data.")

"""## Retrain the model

### Subtask:
Retrain the existing model or a new model using the expanded dataset.

**Reasoning**:
Re-compile and train the existing model using the specified parameters.
"""

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

print("\nStarting model training...")
history = model.fit(
    train_generator,
    steps_per_epoch=train_generator.samples // BATCH_SIZE,
    epochs=EPOCHS,
    validation_data=val_generator,
    validation_steps=val_generator.samples // BATCH_SIZE
)

